from collections.abc import Iterable # used in a conditional to check input in BinaryTree constructor

import sys # parse commandline arguments to display testing information when "debug" is supplied
import unittest # used to write unit tests.

class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left_node = None
        self.right_node = None
        self.size = 0  # Number of nodes in the subtree rooted at this node

        self.parent = None # added to make deleting/updating the tree easier.
        # the implementation otherwise relies on targeting the "parent of..." particular nodes
        # instead of the nodes themselves which feels less readable.
        
        self.height = 0 # added to make code cleaner. otherwise i would just generate height on the
        # fly, zip it up with a list of the nodes then operate on those tuples.

class BinaryTree:
    def __init__(self, values=None):
        """Constructor for BinaryTree class, either creates an empty binary tree or one populated with
           value(s) provided"""

        self.root = None

        if values:
            self.insert(values)
        




    ############################
    # General Helper Functions #
    ############################
    def node_gen(self, order="inorder"):
        """Returns a generator that will traverse the BinaryTree based on the order supplied. Allowed
           values for order: inorder, preorder, postorder, level"""

        # if there's a single element, generator supplies that single element and ceases.
        if self.root and self.root.size == 0:
            yield self.root
        else:
            match order:
                case "inorder": yield from self._node_gen_inorder(self.root)
                case "preorder": yield from self._node_gen_preorder(self.root)
                case "postorder": yield from self._node_gen_postorder(self.root)
                case "level": yield from self._node_gen_level()

    def _node_gen_inorder(self, node):
        """Generator that returns the subtree starting at "node" using the inorder traversal strategy"""

        if node:
            yield from self._node_gen_inorder(node.left_node)
            yield node
            yield from self._node_gen_inorder(node.right_node)

    def _node_gen_preorder(self, node):
        """Generator that returns the subtree starting at "node" using the preorder traversal strategy"""

        if node:
            yield node
            yield from self._node_gen_preorder(node.left_node)
            yield from self._node_gen_preorder(node.right_node)

    def _node_gen_postorder(self, node):
        """Generator that returns the subtree starting at "node" using the postorder traversal strategy"""

        if node:
            yield from self._node_gen_postorder(node.left_node)
            yield from self._node_gen_postorder(node.right_node)
            yield node

    # This feels janky and I kind of hate it. It essentially just sorts the nodes generated by the
    # inorder generator based on their height. It feels unbecoming of a generator because generators
    # seem like they're supposed to only evaluate up until they produce the next value then wait to
    # be called again, but this one consumes the entire inorder generator then produces values from
    # that.
    def _node_gen_level(self):
        """Generator that returns the subtree from the root node using the level-based traversal
           strategy"""

        yield from sorted(self._node_gen_inorder(self.root), key=lambda x: x.height)

    # this approach felt pretty brittle because it relies on sorted to be stable in its output order,
    # but the sorted function appears to be stable. From the python docs:
    #
    # > The built-in sorted() function is guaranteed to be stable. A sort is stable if it guarantees
    # > not to change the relative order of elements that compare equal — this is helpful for sorting
    # > in multiple passes (for example, sort by department, then by salary grade).
    # >
    # > https://docs.python.org/3/library/functions.html#sorted
    #
    # Even if the sorting order were to change, it would cause test cases to fail, so we okay :)


    # because of how frequently i just want a list of the values in a tree, i created a function to
    # convert the node generators to just a list of their values. this is mostly used in unit tests.
    def values_to_list(self, order="inorder"):
        """Returns a list of all the values in the BinaryTree according to the "order" used """

        return list(map(lambda x: x.value, self.node_gen(order)))
        

    # uses the generator defined above and a contraint to find the first (and only) node that has the
    # value being searched for. Used in find and delete. If not found, returns None.
    def find_node(self, value):
        """Returns a node with the value supplied, otherwise returns None"""

        return next((x for x in self.node_gen()
                       if x and x.value == value), None)


                


    ##########
    # Insert #
    ##########
    
    def insert(self, values):
        """Inserts a single value or list of values into BinaryTree while ignoring duplicate values"""

        if not self.find(values):
            if isinstance(values, Iterable):
                for i in values:
                    self._insert(i)
            else:
                self._insert(values)

    # literally the only loop in my implementation! aside from questions of mutability, this is a
    # pretty functional implementation. I could replace the loop with recursive calls that decapitate
    # the list until it's empty, each iteration calling insert on the head of the list. Could also
    # use map/filter just for their effects, but they would require being wrapped in list() because
    # they're iterators which are lazily evaluated.
    #
    # Sometimes a for loop is just the best option :)



    # where the real work happens. if the tree is empty, the inserted value becomes the root node.
    # otherwise it will call a helper function that determines where the new node should be inserted
    # while also contructing a new node with the value being inserted.
    #
    # It then proceeds to insert it on the right side of the parent, then give the child node a pointer
    # to its parent, calculates the height of the child node, then increments the size of the parent.
    def _insert(self, value):
        """Finds the proper insertion point and inserts a node into BinaryTree with the value supplied"""

        if self.root is None:
            self.root = TreeNode(value)
        else:
            if (parent := self._get_insertion_point()) and (child := TreeNode(value)):
                if parent.size == 0:
                    parent.left_node = child

                elif parent.size == 1:
                    parent.right_node = child

                child.parent = parent
                child.height = self._get_height(child)

                parent.size += 1

    # it seems like the standard way to name internal functions in python is beginning with _
    # see: https://peps.python.org/pep-0008/#descriptive-naming-styles


    def _get_insertion_point(self):
        """Returns the node where an insertion should occur in order to maintain a complete binary tree"""

        return self._get_sorted_insertion_points()[0]


    def _get_sorted_insertion_points(self):
        """Returns a list of leaf and non-full branch nodes in the order in which insertion should
           occur in order to maintain a complete binary tree"""

        # uses the inorder generator to return nodes that have one or less children then sorts them
        # based on height.
        return sorted([x for x in self.node_gen(order="inorder")
                         if x.size < 2], key=lambda x: x.height)

    # The reason for the sort can be demonstrated with this tree:
    # 
    #    1
    #  2   3 
    # 4 5
    #
    # The unsorted generator would return the nodes in the order "4, 5, 3" because that's the traversal
    # order. 3 is where the insertion should happen though, and the sorting makes sure that it is the
    # head of list
    #
    # If you have a tree like:
    #  1
    # 2 3
    #
    # the sorting operation won't do anything because 2 and 3 have the same height, so the insertion
    # pont is still correct.


    def _get_height(self, node):
        """Returns the height of the current node"""

        # recurses through the chain of parent pointers until a node doesn't have a parent pointer
        # while adding 1 each recursion.
        return 1 + self._get_height(node.parent) if node.parent else 0


       
    


    ########
    # Find #
    ########

    # wrapper to supply the self.root node to _find. This wrapper is very unnecessary but I like
    # having the user-facing function to be, essentially, a stable interface that hides the underlying
    # implementation
    def find(self, value):
        """Returns true if a node in the BinaryTree has the value being search for"""

        return self._find(value)
        
    # originally i had this implemented to do the searching itself, but it seemed reasonable that a
    # binary tree would have a function to find and return a node so i've piggybacked on that function
    # if find_node returns a node then _find return true, otherwise false.
    def _find(self, value):
        """(Internal Function) Returns true if a node in the BinaryTree has the value being search
           for"""

        return True if self.find_node(value) else False





    ##########
    # Delete #
    ##########
    
    # wrapper for _delete. This one is more justifiable to me than the "find" wrapper because _delete
    # is more than a single line return.
    def delete(self, value):
        """Delete the node with "value" if in the BinaryTree. Otherwise, do nothing."""

        if self.find(value):
            self._delete(value)

    def _delete(self, value):
        """Delete the node with "value" from the tree and maintain complete binary tree"""

        # if single element tree and value matches root then delete root. otherwise call function
        # _replace_node_value which replaces the value of the node to delete with the value from the
        # deepest node then delete the deepest node.
        if self.root.size == 0 and self.root.value == value:
            self.root = None
        else:
            self._replace_node_value(old=self.find_node(value), new=self._find_deepest_node())


    # interestingly, when you find the insertion point, you find the parent of the deepest node. if
    # that parent has a right_node that's the deepest, otherwise the left_node.
    def _find_deepest_node(self):
        """Return the deepest node from the tree"""

        parent = self._get_insertion_point()
        return parent.left_node if parent.right_node is None else parent.right_node


    # takes the node you wanna replace, old, and the node to replace it with, new, then replaces the
    # value in old with new, removes all the pointers to/from new, and decrements the size of the
    # parent of new (because the node is being removed)
    def _replace_node_value(self, old, new):
        """Replace the value of the first argument with the value of the second, and delete the second
           from the BinaryTree"""

        if old is None or new is None:
            print("Error: either the replacing node or the node to be replaced is None")
            return None

        old.value = new.value

        if new.parent.left_node is new:
            new.parent.left_node = None
        elif new.parent.right_node is new:
            new.parent.right_node = None

        new.parent.size -= 1
        new.parent = None





##############
# Test Cases #
##############

# I broke my test cases into specific classes. It is functionally the same as them all being in one
# big one.
class TestFind(unittest.TestCase):
    """TESTING: Unit tests for the BinaryTree's Find Function"""

    def test_empty_tree(self):
        """TESTING: Searching empty BinaryTree"""

        tree = BinaryTree()

        self.assertEqual(tree.find(1), False)


    def test_single_node_item_found(self):
        """TESTING: Searching BinaryTree with a single element that contains element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.find(1), True)


    def test_single_node_item_not_found(self):
        """TESTING: Searching BinaryTree with a single element that does not contain element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.find(2), False)


    def test_item_found(self):
        """TESTING: Searching average BinaryTree that contains element"""

        tree = BinaryTree([1,2,3,4])

        self.assertEqual(tree.find(3), True)


    def test_item_not_found(self):
        """TESTING: Searching average BinaryTree that does not contain element"""

        tree = BinaryTree([1,2,3,4])

        self.assertEqual(tree.find(5), False)



class TestDelete(unittest.TestCase):
    """TESTING: Unit tests for the BinaryTree's Delete Function"""

    def test_delete_empty_tree(self):
        """TESTING: Deleting a value from an empty BinaryTree"""

        tree = BinaryTree()
        tree.delete(1)

        self.assertEqual(tree.root, None)


    def test_delete_root(self):
        """TESTING: Deleting the root element from a BinaryTree with a single element"""

        tree = BinaryTree([1])
        tree.delete(1)

        self.assertEqual(tree.find(1), False)


    def test_delete_root_longer_tree(self):
        """TESTING: Deleting the root element from a longer BinaryTree"""

        tree = BinaryTree([1,2,3,4,5,6,7,8])
        tree.delete(1)

        # most of the tests that insert/delete elements from a tree use the list generated by the
        # values_to_list function with order=level. This makes the test cases more succinct and the
        # level order makes the lists to compare them to easier to write. the generators have unit
        # tests below that should verify their output.
        self.assertEqual(tree.values_to_list(order="level"), [8,2,3,4,5,6,7])


    def test_delete_middle_longer_tree(self):
        """TESTING: Deleting a middle element from a longer BinaryTree"""

        tree = BinaryTree([1,2,3,4,5,6,7,8])
        tree.delete(4)

        self.assertEqual(tree.values_to_list(order="level"), [1,2,3,8,5,6,7])


    def test_delete_tail_longer_tree(self):
        """TESTING: Deleting the last element from a longer BinaryTree"""

        tree = BinaryTree([1,2,3,4,5,6,7,8])
        tree.delete(8)

        self.assertEqual(tree.values_to_list(order="level"), [1,2,3,4,5,6,7])
        



class TestInsert(unittest.TestCase):
    """TESTING: Unit tests for the BinaryTree's Insert Function"""

    def test_insert_empty_list(self):
        """TESTING: Inserting a value into an empty BinaryTree"""

        tree = BinaryTree()
        tree.insert(1)

        self.assertEqual(tree.root.value, 1)


    def test_insert_singlet_list(self):
        """TESTING: Inserting a value into a BinaryTree with a single element"""

        tree = BinaryTree([1])
        tree.insert(2)

        self.assertEqual(tree.values_to_list(order="level"), [1,2])


    def test_insert_longer_list(self):
        """TESTING: Inserting a value into a longer BinaryTree"""

        tree = BinaryTree([1,2,3,4,5,6,7])
        tree.insert(8)

        self.assertEqual(tree.values_to_list(order="level"), [1,2,3,4,5,6,7,8])


    def test_insert_duplicate_item(self):
        """TESTING: Inserting a duplicate value into a BinaryTree"""

        tree = BinaryTree([1])
        tree.insert(1)

        self.assertEqual(tree.values_to_list(order="level"), [1])
        


# Tests for the generators use an empty list, a singlet list, and the following list:
# [5,3,1,8,7,2,6,4]
class TestGenerators(unittest.TestCase):
    """TESTING: Unit tests for the BinaryTree's Generators"""

    def test_inorder_gen_empty(self):
        """TESTING: Inorder Generator generating an empty BinaryTree"""

        tree = BinaryTree()

        self.assertEqual(tree.values_to_list(order="inorder"), [])

    def test_preorder_gen_empty(self):
        """TESTING: Preorder Generator generating an empty BinaryTree"""

        tree = BinaryTree()

        self.assertEqual(tree.values_to_list(order="preorder"), [])

    def test_postorder_gen_empty(self):
        """TESTING: Postorder Generator generating an empty BinaryTree"""

        tree = BinaryTree()

        self.assertEqual(tree.values_to_list(order="postorder"), [])

    def test_level_gen_empty(self):
        """TESTING: Level Generator generating an empty BinaryTree"""

        tree = BinaryTree()

        self.assertEqual(tree.values_to_list(order="level"), [])


    def test_inorder_gen_singlet(self):
        """TESTING: Inorder Generator generating a BinaryTree with a single element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.values_to_list(order="inorder"), [1])

    def test_preorder_gen_singlet(self):
        """TESTING: Preorder Generator generating a BinaryTree with a single element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.values_to_list(order="preorder"), [1])

    def test_postorder_gen_singlet(self):
        """TESTING: Postorder Generator generating a BinaryTree with a single element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.values_to_list(order="postorder"), [1])

    def test_level_gen_singlet(self):
        """TESTING: Level Generator generating a BinaryTree with a single element"""

        tree = BinaryTree([1])

        self.assertEqual(tree.values_to_list(order="level"), [1])


    # generators on longer trees. these trees are 8 elements because in the past my level generator
    # would work on trees up to 7 and break on 8 or more.
    # 
    # [5,3,1,8,7,2,6,4]
    #
    #     5
    #   3   1
    #  8 7 2 6
    # 4
    # 
    # inorder:   [4,8,3,7,5,2,1,6]
    # preorder:  [5,3,8,4,7,1,2,6]
    # postorder: [4,8,7,3,2,6,1,5]
    # level:     [5,3,1,8,7,2,6,4]
    def test_inorder_gen_long(self):
        """TESTING: Inorder Generator generating a longer BinaryTree"""

        tree = BinaryTree([5,3,1,8,7,2,6,4])

        self.assertEqual(tree.values_to_list(order="inorder"), [4,8,3,7,5,2,1,6])

    def test_preorder_gen_long(self):
        """TESTING: Preorder Generator generating a longer BinaryTree"""

        tree = BinaryTree([5,3,1,8,7,2,6,4])

        self.assertEqual(tree.values_to_list(order="preorder"), [5,3,8,4,7,1,2,6])

    def test_postorder_gen_long(self):
        """TESTING: Postorder Generator generating a longer BinaryTree"""

        tree = BinaryTree([5,3,1,8,7,2,6,4])

        self.assertEqual(tree.values_to_list(order="postorder"), [4,8,7,3,2,6,1,5])

    def test_level_gen_long(self):
        """TESTING: Level Generator generating a longer BinaryTree"""

        tree = BinaryTree([5,3,1,8,7,2,6,4])

        self.assertEqual(tree.values_to_list(order="level"), [5,3,1,8,7,2,6,4])
        









if __name__ == "__main__":
    # only runs the unit tests if the executable is supplied "debug" as an argument
    if "debug" in sys.argv:
        # the first positional argument is interpreted by unittest to do something with jupyter and/or
        # python's ikernel. since i am using positional args to indicate debugs should happen it causes
        # an error if i don't supply an empty argv to unittest.main
        unittest.main(argv=[""])


    
        





    # # I designed my program very iteratively and have left the different versions of my find function
    # # down below. feel free to ignore them if you want :)

    
    # # I originally implemented this function in this way, but it felt very ugly and overly
    # # complicated. Anytime I have to use a lot of if/elif/else statements it feels bad man.
    # def _find1(self, node, value):
    #     if node.value == value:
    #         return True
    #     elif node.left_node and node.right_node:
    #         return self._find1(node.left_node, value) or self._find1(node.right_node, value)
    #     elif node.left_node:
    #         return self._find1(node.left_node, value)
    #     elif node.right_node:
    #         return self._find1(node.right_node, value)
            
    #     return False


    # # I think this is significantly more readable than the last one. The base cases are laid out at
    # # the beginning. If there node is None we have reached the end of a subtree and recursion stops.
    # # The other base case is if the node's value is the target value, then we can stop searching because
    # # it's in the tree.
    # #
    # # If the base cases are false, then the function will recursive call itself twice, once for the
    # # node's left child and once for its right, and will or the result of those calls. Since the base
    # # cases return True/False, or-ing them will propagate any True value upward through the function
    # # call stack. 
    # def _find2(self, node, value):
    #     if not node:
    #         return False
    #     if node.value == value:
    #         return True

    #     return self._find2(node.left_node, value) or self._find2(node.right_node, value)

    # # One "issue" with this one is that all the subtrees that the element is not on will be fully
    # # evaluated. It should be fixed with the next iteration though. (actually i think or short-circuits
    # # so this probably isn't true)


    # # third time is the charm. this version uses a generator. generators will generate a single node
    # # at a time from the tree and _find3 will compare the value of that node to the target value. it
    # # originally just generated the values from the nodes but i thought that it could be used in the
    # # delete function so i changed it to nodes.
    # def _find3(self, node, value):
    #     return any(x.value == value for x in self.node_gen())


    # # a fourth version that uses self.find_node laid out below. this one feels the most satisfying
    # # because of code reuse.
    # def _find4(self, node, value):
    #     return True if self.find_node(self.root, value) else False
